apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
      - name: nginx-rs
        image: nginx:latest

