apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /apache
        backend:
          serviceName: apache2
          servicePort: 80
      - path: /nginx
        backend:
          serviceName: nginx-rs
          servicePort: 80
